// PLACEHOLDER FILE.
//
// This file is normally generated by the FlutterFire CLI. Run:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure --project=churchjournal-66f96
//
// That command overwrites this file with real Firebase configuration for the
// registered iOS and Android apps. Until then the values below are placeholders
// so the project keeps compiling; the app will fail to reach Firebase at runtime
// if these are not replaced.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web. '
        'Run flutterfire configure to regenerate firebase_options.dart.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform. '
          'Run flutterfire configure to regenerate firebase_options.dart.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUbtKYsVpVy-lC0Mb9ldq__INK8VoKvkk',
    appId: '1:1016089587594:android:e985e2bb8511f5bd08e273',
    messagingSenderId: '1016089587594',
    projectId: 'churchjournal-66f96',
    storageBucket: 'churchjournal-66f96.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhdHMpXlHKe6ZHTnRk-lsqorsEPgLzMrc',
    appId: '1:1016089587594:ios:9da12a12ddab4f4c08e273',
    messagingSenderId: '1016089587594',
    projectId: 'churchjournal-66f96',
    storageBucket: 'churchjournal-66f96.firebasestorage.app',
    androidClientId: '1016089587594-c3n4ej180anbapn7i7gnd50fm7s0je3e.apps.googleusercontent.com',
    iosClientId: '1016089587594-6gjplpslj33aij2271um1lmiknh20ggh.apps.googleusercontent.com',
    iosBundleId: 'com.churchjournal.app',
  );
}
